---
name: CI
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  repo-lint:
    name: Repository Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: .
          strict: true
          no_warnings: false
          config_file: .yamllint
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        env:
          SHELLCHECK_OPTS: -s bash
        with:
          format: tty
  build:
    strategy:
      fail-fast: false
      matrix:
        project:
          - node.js
        node:
          - 14
          - 16
          - 18
    name: Build ${{ matrix.project }} ${{ matrix.node }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          architecture: x64
          cache-dependency-path: ${{ matrix.project }}/package-lock.json
      - name: Install node modules
        working-directory: ${{ matrix.project }}
        run: npm ci
      - name: Lint source code
        working-directory: ${{ matrix.project }}
        run: npm run eslint
